#ifndef AST3ROIDS_CONSTANTESGLOBALES_HPP
#define AST3ROIDS_CONSTANTESGLOBALES_HPP

#include <SFML/System.hpp>

static sf::Vector2u RESOLUCION_BASE = {800, 600};

#endif //AST3ROIDS_CONSTANTESGLOBALES_HPP
