#ifndef AST3ROIDS_ESTADOS_HPP
#define AST3ROIDS_ESTADOS_HPP

enum EstadoNave { REPOSO , ACELERANDO , DESTRUIDA, REAPARECIENDO };
enum EstadoOvni {VIVO, EXP1, EXP2, EXP3, MUERTO};
enum Tipo {TIPO_0, TIPO_1, TIPO_2};
enum Tamano {TAM_0 = 10, TAM_1 = 20, TAM_2 = 40};

#endif //AST3ROIDS_ESTADOS_HPP
